---
- name: install mariadb gpg key
  apt_key: url='http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x{{ mariadb_gpg_key_id }}' state=present
  # apt_key: keyserver="keyserver.ubuntu.com" id={{ mariadb_gpg_key_id }} state=present # Ansible 1.6

- name: add mariadb deb repository
  apt_repository: repo='deb http://ftp.igh.cnrs.fr/pub/mariadb/repo/{{ mariadb_series_version }}/debian {{ debian }} main' state=present

- name: install mariadb packages
  apt: pkg={{ item }} state=latest update_cache=yes force=yes
  with_items:
      - mariadb-server
      - mytop
  notify: restart mariadb
